# Generated by Django 3.2 on 2021-04-12 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_user_is_super'),
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=255, unique=True)),
                ('r_restriction', models.CharField(max_length=511)),
            ],
            options={
                'db_table': 'gp_road',
            },
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_plate', models.CharField(max_length=32)),
                ('p_time', models.DateTimeField(auto_now=True)),
                ('p_against', models.BooleanField(default=False)),
                ('p_roads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.road')),
                ('p_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
            options={
                'db_table': 'gp_plate',
            },
        ),
    ]
