# Generated by Django 3.2 on 2021-04-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='p_is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='road',
            name='r_is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
