# Generated by Django 3.1.7 on 2021-03-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_username', models.CharField(max_length=12, unique=True)),
                ('u_password', models.CharField(max_length=255)),
                ('u_email', models.EmailField(max_length=75)),
                ('u_icon', models.ImageField(upload_to='icons/%Y%m%d')),
                ('is_active', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'gp_user',
            },
        ),
    ]
